theme: jekyll-theme-minimal
description: ArgoUML resources provided by Github. Created from copies of the information at Tigris.
google_analytics: UA-682460-2
markdown: kramdown
logo: /tigris/argouml/images/argologo200x190.png
old_tigris_title: Old site copied from Tigris
old_tigris_description: This is the old stale information copied from tigris.org. Expect a lot of links to not be working.

